#!/usr/bin/env python3
"""
landver - a validation tool for land
"""
import Common_functions as util
from sys import argv
import LANDVER_pre
import LANDVER


def landver_main():
    parser = util.get_parser(__doc__) #in Common_functions
    args = parser.parse_args(argv[1:])
    cfg = util.get_configuration(args.options_file) #in Common_functions

    print(cfg)

    #  Preprocess data:
    LANDVER_pre.preprocessData(cfg)

    for land_type in cfg.land_classes:

        for val_times in cfg.validation_times:

          df = None

          #  Validate sensible heat flux
          if cfg.validate_SH:
            df = LANDVER.in_situ_validation(cfg, "SH", val_times, land_type, df)

          #  Validate latent heat flux
          if cfg.validate_LH:
            df = LANDVER.in_situ_validation(cfg, "LH", val_times, land_type, df)
            
          print("df to create html")
          print(df)
          util.web_create(cfg, val_times, land_type, df)


if __name__ == "__main__":
    landver_main()
